name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
           login-server: ${{ rkazurecontainerregistry.azurecr.io }}
           username: ${{ rkazurecontainerregistry }}
           password: ${{ 6UHOnUbux4pqIoJPA37y2BUxs/zSN+NFfgVmO16rfO+ACRADxjD5 }}
      - run: |
          docker build . -t ${{ rkazurecontainerregistry.azurecr.io }}/azurekubernatives:${{ github.sha }}
          docker push ${{ rkazurecontainerregistry.azurecr.io }}/azurekubernatives:${{ github.sha }}
